substitutions:
  _PROJECT_ID: ecencia-andina-preprod
  _REGION: us-central1
  _REPO: ecencia
  _IMAGE: frontend
  _TAG: preprod
  _VITE_API_BASE_URL: ''

steps:
  - name: node:22.22.3-slim
    entrypoint: npm
    args: ['ci']

  - name: node:22.22.3-slim
    entrypoint: npm
    args: ['audit', '--audit-level=moderate']

  - name: node:22.22.3-slim
    entrypoint: npm
    args: ['test']

  - name: node:22.22.3-slim
    entrypoint: npm
    args: ['run', 'lint']

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - PUBLIC_API_BASE_URL=${_VITE_API_BASE_URL}
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:${_TAG}
      - .

  - name: aquasec/trivy:0.71.0
    args:
      - image
      - --timeout
      - 20m
      - --exit-code
      - '1'
      - --severity
      - HIGH,CRITICAL
      - --scanners
      - vuln
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:${_TAG}

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:${_TAG}

timeout: 1800s
