substitutions:
  _PROJECT_ID: eciencia-andina-preprod
  _REGION: us-central1
  _REPO: eciencia
  _IMAGE: frontend
  _TAG: preprod
  _VITE_API_BASE_URL: ''
  _VITE_SUPABASE_URL: ''
  _VITE_SUPABASE_PUBLISHABLE_KEY: ''
  _VITE_SUPABASE_PROJECT_ID: ''

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - PUBLIC_API_BASE_URL=${_VITE_API_BASE_URL}
      - --build-arg
      - PUBLIC_SUPABASE_URL=${_VITE_SUPABASE_URL}
      - --build-arg
      - PUBLIC_SUPABASE_VALUE=${_VITE_SUPABASE_PUBLISHABLE_KEY}
      - --build-arg
      - PUBLIC_SUPABASE_PROJECT_ID=${_VITE_SUPABASE_PROJECT_ID}
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:${_TAG}
