version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecencia-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./convenios:/usr/src/convenios
