version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecencia-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./convenios:/usr/src/convenios

  telegram_bot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecencia-telegram-bot
    restart: always
    command: node poll_telegram.js
    env_file:
      - ./backend/.env

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: ecencia-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=ecenciaapp.eastus2.cloudapp.azure.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - WEBHOOK_URL=https://ecenciaapp.eastus2.cloudapp.azure.com/n8n/
      - N8N_PATH=/n8n/
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/n8n/.n8n:/home/node/.n8n
