sonar.organization=packeins
sonar.projectKey=packeins_EcenciaAndinaAPP
sonar.projectName=EcenciaAndinaAPP
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend
sonar.tests=backend/src/test,frontend/src
sonar.test.inclusions=backend/src/**/*.test.js,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx

# Exclusiones para evitar escanear librerias, binarios y reportes
sonar.exclusions=backend/node_modules/**,frontend/node_modules/**,backend/coverage/**,frontend/coverage/**,frontend/dist/**,**/*.sql,**/*.png,**/*.ico
sonar.coverage.exclusions=backend/src/test/**,frontend/src/test/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
