create or replace function public.eciencia_normalize_phone(value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case
    when digits = '' then null
    when digits like '00%' then substring(digits from 3)
    when digits like '593%' then digits
    when length(digits) = 10 and digits like '0%' then '593' || substring(digits from 2)
    else digits
  end
  from (select regexp_replace(coalesce(value, ''), '[^0-9]', '', 'g') as digits) normalized;
$$;

alter table public.roles alter column id_rol set generated by default;
alter table public.categorias_productos alter column id_categoria set generated by default;
alter table public.productos alter column id_producto set generated by default;
alter table public.tipos_cliente alter column id_tipo_cliente set generated by default;
alter table public.estados_orden alter column id_estado set generated by default;
alter table public.origenes_pedido alter column id_origen set generated by default;
alter table public.categorias_menu alter column id_categoria_menu set generated by default;
alter table public.alimentos alter column id_alimento set generated by default;

alter table public.empleados
  drop constraint if exists empleados_id_fkey;

alter table public.empleados
  add constraint empleados_id_fkey
  foreign key (id)
  references auth.users(id)
  on delete cascade;

alter table public.clientes_convenios
  drop constraint if exists clientes_convenios_id_cliente_fkey;

alter table public.clientes_convenios
  add constraint clientes_convenios_id_cliente_fkey
  foreign key (id_cliente)
  references public.clientes(id_cliente)
  on delete cascade;

alter table public.clientes_convenios
  drop constraint if exists clientes_convenios_id_convenio_fkey;

alter table public.clientes_convenios
  add constraint clientes_convenios_id_convenio_fkey
  foreign key (id_convenio)
  references public.convenios(id_convenio)
  on delete cascade;

alter table public.conveniohistorial
  drop constraint if exists conveniohistorial_id_convenio_fkey;

alter table public.conveniohistorial
  add constraint conveniohistorial_id_convenio_fkey
  foreign key (id_convenio)
  references public.convenios(id_convenio)
  on delete cascade;

alter table public.detalle_orden
  drop constraint if exists detalle_orden_id_orden_fkey;

alter table public.detalle_orden
  add constraint detalle_orden_id_orden_fkey
  foreign key (id_orden)
  references public.ordenes(id_orden)
  on delete cascade;

alter table public.saldos_servicio
  drop constraint if exists saldos_servicio_id_cliente_fkey;

alter table public.saldos_servicio
  add constraint saldos_servicio_id_cliente_fkey
  foreign key (id_cliente)
  references public.clientes(id_cliente)
  on delete cascade;

alter table public.saldos_servicio
  drop constraint if exists saldos_servicio_id_producto_fkey;

alter table public.saldos_servicio
  add constraint saldos_servicio_id_producto_fkey
  foreign key (id_producto)
  references public.productos(id_producto)
  on delete cascade;

update public.tipos_cliente set nombre_tipo = 'Cliente directo' where id_tipo_cliente = 1;
update public.tipos_cliente set nombre_tipo = 'Convenio' where id_tipo_cliente = 2;

update public.clientes
set telefono = public.eciencia_normalize_phone(telefono)
where telefono is distinct from public.eciencia_normalize_phone(telefono);

create unique index if not exists uq_clientes_active_normalized_phone
  on public.clientes (public.eciencia_normalize_phone(telefono))
  where esta_activo is true and telefono is not null;

create unique index if not exists uq_clientes_convenios_one_per_client
  on public.clientes_convenios (id_cliente);

create index if not exists idx_ordenes_created_estado
  on public.ordenes (created_at desc, id_estado);

create index if not exists idx_ordenes_cliente_created
  on public.ordenes (id_cliente, created_at desc);

create index if not exists idx_clientes_convenios_convenio_cliente
  on public.clientes_convenios (id_convenio, id_cliente);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.convenios'::regclass
      and conname = 'chk_convenios_date_range'
  ) then
    alter table public.convenios
      add constraint chk_convenios_date_range
      check (fecha_caducidad >= fecha_inicio) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.conveniohistorial'::regclass
      and conname = 'chk_conveniohistorial_date_range'
  ) then
    alter table public.conveniohistorial
      add constraint chk_conveniohistorial_date_range
      check (fecha_caducidad >= fecha_inicio) not valid;
  end if;
end;
$$;

do $$
declare
  item record;
begin
  for item in
    select n.nspname as schema_name, c.relname as table_name, con.conname as constraint_name
    from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and con.contype = 'c'
      and not con.convalidated
  loop
    execute format(
      'alter table %I.%I validate constraint %I',
      item.schema_name,
      item.table_name,
      item.constraint_name
    );
  end loop;
end;
$$;

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'alimentos',
    'categorias_menu',
    'categorias_productos',
    'clientes',
    'clientes_convenios',
    'conveniohistorial',
    'convenios',
    'detalle_orden',
    'empleados',
    'estados_orden',
    'menu_diario',
    'menu_settings',
    'ordenes',
    'origenes_pedido',
    'productos',
    'recargas_saldo',
    'roles',
    'saldos_servicio',
    'telegram_bot_state',
    'telegram_order_traces',
    'telegram_subscriptions',
    'tipos_cliente'
  ] loop
    execute format('alter table public.%I enable row level security', target_table);
    execute format(
      'drop policy if exists %I on public.%I',
      'deny_direct_data_api_access',
      target_table
    );
    execute format(
      'create policy %I on public.%I as restrictive for all to anon, authenticated using (false) with check (false)',
      'deny_direct_data_api_access',
      target_table
    );
  end loop;
end;
$$;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant usage, select on sequences to service_role;

do $$
begin
  if to_regprocedure('n8n.increment_workflow_version()') is not null then
    execute 'alter function n8n.increment_workflow_version() set search_path = ''''';
  end if;
end;
$$;
